global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['https://nhl-reporting-app-b1fe017be8db.herokuapp.com/metrics']