global:
  scrape_interval: 15s  # How often to scrape targets by default.

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['nhl-reporting-app.herokuapp.com:443']  # Replace with your app's metrics endpoint
        labels:
          env: production
